project:
  type: book
  output-dir: ../docs


book:
  title: "Outil de r√©servation des repas"
  author: "Guillaume Gilles"
  date: "2025-12-14"
  repo-url: https://github.com/jjallaire/hopr/
  repo-actions: [edit, source, issue]
  downloads: [pdf]
  chapters:
    - index.qmd
    - db.qmd

format:
  html:
    theme: cosmo
